<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.30367299 0.28277556 0.33027895 ... 0.22335718 0.75977985 0.26395393]
 [0.28784126 0.08509055 0.85640397 ... 0.37719093 0.26777442 0.33314112]
 [0.4558872  0.92259393 0.67178137 ... 0.08499772 0.61847361 0.04610409]
 ...
 [0.12092406 0.03061601 0.89647322 ... 0.81122528 0.43753052 0.67646406]
 [0.15667359 0.17542134 0.05833514 ... 0.86408347 0.63040163 0.34084154]
 [0.14902466 0.59053489 0.18381542 ... 0.76636441 0.14649682 0.31820343]]
[[0.19558559 0.96908228 0.34755669 ... 0.06631969 0.26354358 0.28357807]
 [0.80180613 0.19091979 0.94774523 ... 0.67401068 0.94204592 0.79069477]
 [0.47845685 0.7895639  0.35149577 ... 0.97203498 0.75884916 0.29301534]
 ...
 [0.20772364 0.12050868 0.92332575 ... 0.34133668 0.62857224 0.26025638]
 [0.81890878 0.61903912 0.08873629 ... 0.10487703 0.18164735 0.37261978]
 [0.44256191 0.78208579 0.32205199 ... 0.66046311 0.5331934  0.35710518]]


In [ ]:
def mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    # pass

    a = a.tolist()
    b = b.tolist()

    c = [[0 for j in range(len(b[0]))] for i in range(len(a))]
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                c[i][j] += a[i][k] * b[k][j]
    return c

In [ ]:
def np_mult(a, b):
    """  
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    # pass
    # c = a @ b
    return a @ b

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 233 ms, sys: 0 ns, total: 233 ms
Wall time: 236 ms


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 672 µs, sys: 4.71 ms, total: 5.38 ms
Wall time: 11.8 ms


In [ ]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.43748844 0.92578831 0.19757005] [0.83674714 0.72691702 0.01399986]


In [ ]:
def scalar_product(a, b):
    """  
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """ 

    a = a.tolist()
    b = b.tolist()

    # pass
    # c = 0
    # for i in range(len(a)):
    #   for j in range(len(b)):
    #     if i == j:
    #       c += a[i] * b[j]
    
    c = sum([x*y for x,y in zip(a,b)])

    return c

In [ ]:
def np_scalar_product(a,b):
    """  
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """ 
    # pass
    # return sum(np.multiply(a,b))
    return a @ b
    # return a.dot(b)

In [ ]:
%timeit product_1 = scalar_product(a,b)
%timeit product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

1.18 µs ± 12.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.29 µs ± 21.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [2]:
def np_diag_2k(a):
    """  
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    # pass
    a[a%2==1] = 0
    return np.trace(a)

In [3]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[6, 3, 7, 4, 2],
       [8, 3, 4, 4, 9],
       [1, 3, 5, 2, 3],
       [5, 2, 6, 4, 1],
       [1, 2, 8, 3, 7]])

In [4]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 123 µs, sys: 17 µs, total: 140 µs
Wall time: 145 µs


10

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [24]:
def cumsum(A):
    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    # pass
    # a_len = max(A.shape)
    # a_len_sqrt = int(np.sqrt(a_len))
    # A = A.reshape((a_len_sqrt, a_len_sqrt))
    # return np.cumsum(A, axis=1)
    return np.cumsum(A)

In [25]:
# зададим некоторую последовательность и проверим ее на вашей функции. 
A = sps.uniform.rvs(size=10**3) 

%time S2 = cumsum(A)

CPU times: user 43 µs, sys: 6 µs, total: 49 µs
Wall time: 54.4 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [53]:
from copy import copy
def np_transformation(X, a=1):
    """  
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и 
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    # pass
    A = X.copy()
    A[:,1::2] = a
    # A[:,::2] = A[:,::-2]**3
    A[:,::2] = np.power(A[:,::-2], 3)
    X = np.concatenate((X,A),axis=1)
    return X

    # def transform(X, a=1):
    # Y = np.copy(X)
    # Y[:,1::2] = a
    # Y[:,0::2] **= 3
    # return np.hstack((X, Y[:,::-1]))

    # def transform(X, a=1):
    # x = [np.flip([string[i] ** 3 if i % 2 == 0 else a for i in range(len(string))], 0) for string in X]
    # return np.concatenate((X, x), axis=1)

In [54]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = np_transformation(X, 5)

CPU times: user 136 µs, sys: 18 µs, total: 154 µs
Wall time: 120 µs


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [70]:
def np_encode(a):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    # pass
    ia = np.asarray(a)                # force numpy
    n = len(ia)
    if n == 0: 
        # return (None, None, None)
        return (None, None)
    else:
        y = ia[1:] != ia[:-1]               # pairwise unequal (string safe)
        i = np.append(np.where(y), n - 1)   # must include last element posi
        z = np.diff(np.append(-1, i))       # run lengths
        # p = np.cumsum(np.append(0, z))[:-1] # positions
        # return(z, p, ia[i])
        return (ia[i], z)

    # def encode(a):
    # is_new_in_row = np.array(a[1:] != a[:-1])
    # position = np.append(np.where(is_new_in_row), len(a) - 1)
    # lengths = np.diff(np.append(-1, position))
    # return (a[position], lengths)

    # def encode(a):
    # a = np.array(a)
    # numbers, counter, last = [], [], None
    # for num in a:
    #     if num != last:
    #         last = num
    #         numbers.append(num)
    #         counter.append(1)
    #     else:
    #         counter[-1] += 1
    # return numbers, counter

    # def encode(a):
    # z = np.arange(a.size)[a != np.append(a[1:], a[-1])]
    # result = (np.append(a[z], a[-1]), np.append(z, a.size - 1) - np.insert(z, 0, -1))
    # return result

In [71]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

CPU times: user 495 µs, sys: 0 ns, total: 495 µs
Wall time: 501 µs
